---
- name: Ping target machine(s) and print message
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Ping target machine(s)
      ansible.builtin.ping:

    - name: Print confirmation
      ansible.builtin.debug:
        msg: Ping successful

    - name: Print facts
      ansible.builtin.debug:
        var: ansible_facts