- name: Reboot remote
  hosts: all
  become: true
  remote_user: "{{ lookup('ansible.builtin.ini', 'target_deploy_user', type='properties', file=playbook_dir ~ '/../../.env') | default('ansible_user', true) }}"
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
    
    - name: Print success
      ansible.builtin.debug:
        msg: Rebooting...