- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - ufw
    state: present

- name: Add GPG key
  ansible.builtin.shell:
    cmd: |
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc

- name: Add the repository to Apt sources
  ansible.builtin.shell:
    cmd: |
      tee /etc/apt/sources.list.d/docker.sources <<EOF
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
      Components: stable
      Architectures: $(dpkg --print-architecture)
      Signed-By: /etc/apt/keyrings/docker.asc
      EOF

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Add "{{ target_deploy_user }}" to docker group
  ansible.builtin.user:
    name: "{{ target_deploy_user }}"
    groups: docker
    append: true